AM_CPPFLAGS = \
	-Wno-deprecated-declarations \
	-I$(top_srcdir)/lwadvapi/include \
	-I$(top_srcdir)/lwadvapi/include/public \
	-I$(top_srcdir)/lwmsg/include \
	-I$(top_srcdir)/lwbase/include

noinst_LTLIBRARIES = liblwadvapi_dscache.la

liblwadvapi_dscache_la_SOURCES = \
       lwdscache.c

liblwadvapi_dscache_la_CPPFLAGS = $(AM_CPPFLAGS)
liblwadvapi_dscache_la_LIBADD =
liblwadvapi_dscache_la_LDFLAGS =
