AM_CPPFLAGS = \
	-I$(top_srcdir)/lwadvapi/include \
	-I$(top_srcdir)/lwadvapi/include/public \
	-I$(top_srcdir)/lwmsg/include \
	-I$(top_srcdir)/lwbase/include

noinst_LTLIBRARIES = liblwadvapi_file.la

liblwadvapi_file_la_SOURCES = \
       lwfile.c

liblwadvapi_file_la_CPPFLAGS = $(AM_CPPFLAGS)
liblwadvapi_file_la_LIBADD =
liblwadvapi_file_la_LDFLAGS =
